services:
  postgres:
    image: postgres:15
    container_name: silvahr_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: silvahr_db
    ports:
      - "5432:5432"

volumes:
  pgdata: