spring.application.name=silvahr
server.port=5001

spring.datasource.url=jdbc:postgresql://localhost:5432/silvahr_db
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.show-sql=true
spring.jpa.hibernate.dialect= org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
